name: fintrack
description: A Goal planner.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

#----------------PACKAGES-------------------#
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0


  #Icons
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^16.3.2
  flutter_timezone: ^1.0.8
  rxdart: ^0.27.7
  iconsax: ^0.0.8
  pie_chart: ^5.4.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  http: ^1.2.0
  provider: ^6.1.1

  flutter_bloc: ^8.1.3
  email_validator: ^2.1.17
  flutter_secure_storage: ^9.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

#----------------LOCAL ASSETS-------------------#
  assets:
    - assets/logos/F.png
    - assets/logos/facebook-icon.png
    - assets/logos/google-icon.png

